# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  lcrypt_config = debug
endif
ifeq ($(config),release)
  lcrypt_config = release
endif

PROJECTS := lcrypt

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

lcrypt:
ifneq (,$(lcrypt_config))
	@echo "==== Building lcrypt ($(lcrypt_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(lcrypt_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lcrypt"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"